import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true} className="h-full">
        <body
          className={cn(
            "relative h-full font-sans antialiased",
            inter.className
          )}
        >
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey="healthcare-theme"
          >
            <main className="relative flex flex-col min-h-screen">
              {/* <Navbar /> */}
              {/* <NavMenu /> */}

              <div className="flex-grow flex-1">{children}</div>

              {/* <Footer />
              <Toaster position="top-center" richColors /> */}
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
